name: Main Workflow
on:
  push:
    branches:
      - main
      - develop
      - githubactions-moves
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  check:
    needs: build
    uses: ./.github/workflows/check.yml

  publish:
    if: github.ref == 'refs/heads/main'
    needs: check
    uses: ./.github/workflows/publish.yml
