name: Publish
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4

      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}

      - name: Gather files
        run: |
          rm -f *.md *.html
          mv ~/static/* ./
          mv snapshot.html index.html
          mkdir content
          shopt -s extglob
          mv !(content) content

      - name: Push to docs.geostandaarden.nl
        run: |
          git clone https://github.com/Geonovum/docs.geostandaarden.nl.git docs-repo
          cd docs-repo
          git config user.name "GitHub Action"
          git config user.email "deploy-bot@geonovum.nl"
          cp -r ../index.html ../content .
          git add -A
          git commit -m "Automated Release from $GITHUB_REPOSITORY"
          git push
