name: Publish
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    environment:
      name: production
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}

      - name: Gather files
        run: |
          rm -f *.md *.html
          mv ~/static/* ./
          mv snapshot.html index.html
          mkdir content
          shopt -s extglob
          mv !(content) content

      - name: Genereer branchnaam
        id: branch
        run: echo "name=auto-update-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Clone PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'Geonovum'
          repository: 'docs.geostandaarden.nl'
          branch: ${{ steps.branch.outputs.name }}
          access-token: ${{ secrets.GH_PUSH_TOKEN }}
      - name: Kopieer gegenereerde output naar docs repo
        run: |
          cp -r index.html content docs.geostandaarden.nl/
      - name: Maak PR aan
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}
          path: docs.geostandaarden.nl
          branch: ${{ steps.branch.outputs.name }}
          title: "Automated update from ${{ github.repository }}"
          body: "Automatisch gegenereerde publicatie-update vanuit [${{ github.repository }}](https://github.com/${{ github.repository }})"
          base: main