name: Publish
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    environment: production
#    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4

      - name: Recover HTML
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}

      - name: Gather files
        run: |
          rm -f *.md *.html
          mv ~/static/* ./
          mv snapshot.html index.html
          mkdir content
          shopt -s extglob
          mv !(content) content
      - name: Debug secret beschikbaarheid
        run: |
          if [ -z "${{ secrets.GH_PUSH_TOKEN }}" ]; then
            echo "❌ GH_PUSH_TOKEN is NIET beschikbaar in deze workflow!"
            exit 1
          else
            echo "✅ GH_PUSH_TOKEN is correct geladen."
          fi

      - name: Create branch and PR in docs repo
        env:
          GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          # Config
          REPO="Geonovum/docs.geostandaarden.nl"
          BRANCH="auto-update-$(date +'%Y%m%d%H%M%S')"
          TARGET_DIR="docs-repo"
          COMMIT_MSG="Automated update from $GITHUB_REPOSITORY"
          
          # Clone repo
          git clone https://x-access-token:${{ env.GH_PUSH_TOKEN }}@github.com/$REPO.git $TARGET_DIR
          cd $TARGET_DIR

          # Maak branch
          git checkout -b $BRANCH

          # Kopieer output
          cp -r ../index.html ../content .

          # Commit en push
          git config user.name "Geonovum CI"
          git config user.email "noreply@geonovum.nl"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "$COMMIT_MSG"
            git push origin $BRANCH
      
            gh pr create --base main --head $BRANCH \
            --title "$COMMIT_MSG" \
            --body "Automatisch gegenereerde publicatie-update vanuit [$GITHUB_REPOSITORY](https://github.com/$GITHUB_REPOSITORY)"
          else
          echo "Geen wijzigingen om te committen. PR wordt niet aangemaakt."
          fi
